xdaysaysay_admin_irc_server_index:
    path:     /
    defaults:
        _controller: "XdaysaysayAdminBundle:IRCServer:index"
        search: ''
    options:
        expose: true

xdaysaysay_admin_irc_server_new:
    path:     /new
    defaults: { _controller: "XdaysaysayAdminBundle:IRCServer:new" }

xdaysaysay_admin_irc_server_edit:
    path:     /{id}/edit
    defaults: { _controller: "XdaysaysayAdminBundle:IRCServer:edit" }

xdaysaysay_admin_irc_server_delete_confirm:
    path:     /{id}/delete/confirm
    defaults: { _controller: "XdaysaysayAdminBundle:IRCServer:deleteConfirm" }
    methods:  [GET]

xdaysaysay_admin_irc_server_delete:
    path:     /{id}/delete
    defaults: { _controller: "XdaysaysayAdminBundle:IRCServer:delete" }
    methods:  [DELETE]