xdaysaysay_admin:
    resource: "@XdaysaysayAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

xdaysaysay_user:
    resource: "@XdaysaysayUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

avanzu_admin_home:
    path: /admin

avanzu_admin_profile:
    path: /profile/{userid}/

avanzu_admin_logout:
    path: /logout